### ISSUE TITLE
Styling fixes to community profile pages

### ISSUE THREAD

**Issue by arouault** [MAPC/datacommon#165]
There are lots of small tweaks to the UI of community profiles: 

- [x] inconsistent spacing for chart labels under environment tab
![screen shot 2018-08-28 at 11 59 04 am](https://user-images.githubusercontent.com/1305629/44735302-0fc4e100-aaba-11e8-8bc2-8e987867ba15.png)

- [x] over enlarged chart and labels, and overlapping label lines on chart under governance
![screen shot 2018-08-28 at 12 01 27 pm](https://user-images.githubusercontent.com/1305629/44735443-882ba200-aaba-11e8-89b3-7913e633b90c.png)

- [x] Under education tab, legends under charts are aligned differently. Overlapping labels. 
![screen shot 2018-08-28 at 12 05 09 pm](https://user-images.githubusercontent.com/1305629/44735571-de98e080-aaba-11e8-9df2-8b1f9786ced7.png)

- [x] Wrong font used in one chart under housing tab: 
![screen shot 2018-08-28 at 12 07 27 pm](https://user-images.githubusercontent.com/1305629/44735684-23247c00-aabb-11e8-9d41-86504bc60a2e.png)

- [x] Under transportation tab: Overlapping lines in pie chart. Sizing is way too small. 
![screen shot 2018-08-28 at 12 09 10 pm](https://user-images.githubusercontent.com/1305629/44735718-3899a600-aabb-11e8-8397-5dc74febf336.png)

**Comment by deedeekim** [comment]
General comments across all tabs: 
- [ ] Can we change the municipal polygon stroke to 1 px instead of 2px
- [ ] The axis numbers are the incorrect font (they look like Arial and not Skolar Sans)
- [ ] Axis labels should be bold (font-weight: 700)
- [ ] Apply consistent bar width across all tabs - we like the Housing tab widths
- [ ] Remove bold from source names (font-weight:400)
- [ ] Update colors for charts (see color logic below) 
![colorlogic_dc](https://user-images.githubusercontent.com/25641695/44927899-1d7d9f00-ad24-11e8-8db9-a990d0ca01d6.png)

Here are some of the same points from above but in context 

![artboard 1](https://user-images.githubusercontent.com/25641695/44927983-6170a400-ad24-11e8-94db-269048ed4b16.png)

![artboard 3](https://user-images.githubusercontent.com/25641695/44927987-65042b00-ad24-11e8-9c6c-e6141a1a5455.png)

Color change for economy chart:
![artboard 5](https://user-images.githubusercontent.com/25641695/44928221-363a8480-ad25-11e8-94bc-c531640269b4.png)
