### ISSUE TITLE
Create Upload Interface

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#217]
**Describe the feature. What should a user be able to do?**
As a user I should be able to enter metadata and choose a file to upload. Then it should upload to and display on the website.

**Comment by mzagaja** [comment]
We might have to specify the month and year in the metadata fields for this because the front end is going to need to be able to appropriately sort these by date.

**Comment by atomtay** [comment]
Is the goal for this to work in tandem with #328 to maintain a second, private data browser (and thus put a GUI around some of the work that Guy does)? I think that when it was first opened, the thought was to have a login and upload feature so that calendar entries could be uploaded as PDFs, but we've since gone towards interactive visualizations instead of static files in that regard.

**Comment by mzagaja** [comment]
Yeah this was about uploading calendar PDFs. I am going to close this since it is moot given the change in direction on the calendar. If we want to have a web interface for Guy's work then we can make a new issue.
