### ISSUE TITLE
Update charts to latest data and automate so that always pulling the most recent data.

### ISSUE THREAD

**Issue by japartridge** [MAPC/datacommon#351]
I'm noticing that all the ACS data is still 2012-16; other datasets too (ES-202, DESE, etc.)

**Comment by atomtay** [comment]
So it seems that the data fetched is up-to-date, but the label is out of date. It's statically taken from the `timeframe` variables in the file `app/javascript/pages/constants/charts.js`. A quick immediate fix would be updating all of those values, but that would require continuous updates whenever new 5-year estimates come out.

**Comment by japartridge** [comment]
oh interesting! well that's better than what i thought was happening. there should be a way to pull the latest date from the metadata, but not sure how much dev time that involves.

**Comment by atomtay** [comment]
Yeah, I'm re-learning my way around the various PRQL calls in looking through this. I'm going to go ahead and get everything up-to-date through the constants file I mentioned above, and hopefully I'll have a better idea what would be involved in a generalized solution after that.

**Comment by atomtay** [comment]
I was able to update most of the charts (some were already up-to-date, most just needed updated labels, a couple needed pointers to more recent data), but there are two that are still a bit troublesome:
1) "Employment by Industry", under "Economy." The chart seems to pull 2001-2018 data, but the datasource ([Occupational Employment and Wages by Industry (NAICS) (MA)](https://datacommon.mapc.org/browser/datasets/319)) only displays 2005-2016 data. I tried looking through the results of the PRQL query, but haven't found where those extra years come from.
2) "Hypertension Hospitalizations by Race" under "Public Health." The current data shows the 2008-2012 data, but the datasource ([Hypertension Related Hospitalizations (Municipal)](https://datacommon.mapc.org/browser/datasets/385)) doesn't completely load---it errors out with `column "years" does not exist`.

**Comment by atomtay** [comment]
Still not sure what to do about the second chart, but the issue with the first chart is a link to the incorrect dataset; it's actually pulling from [2 Digit Sector: Employment & Avg Wkly Wages (Municipal)](https://datacommon.mapc.org/browser/datasets/387), which does has 2001-2018 data. Using the Occupational Employment and Wages by Industry dataset (linked above) would require some re-structuring of the chart, as the 2005-2016 data is all bucketed together while the 2 Digit Sector data splits it up by year.

**Comment by japartridge** [comment]
2 digit sectors are just fine for this chart 👍 not sure I can be any help with the error on the second chart, but I can take a look at the data.

**Comment by atomtay** [comment]
I'm about to post a PR to update the data and labels for out-of-date charts (the hypertension hospitalizations chart error turned out to be a PRQL misfire, easily fixed, and the data was up-to-date anyway), but that still leaves the question of automatically updating the charts. Aside from the two edge cases, updating the labels didn't take too long (couple hours or so to check all the datasets), and as long as we're pulling data from PRQL there isn't a clear way to further automate things.

I would propose setting up a Slack reminder (maybe every 6 months or so) for us to check the datasets and see if new data has been posted. I think it would take several years before the time spent manually checking would outpace the development time needed to further examine automation, and by that point we might have moved away from PRQL and could take this feature into consideration with whatever future system we use.

**Comment by japartridge** [comment]
sounds like a reasonable solution to me.

Jessie Partridge Guerrero
Cell: 781-526-7997
Sent from my mobile
________________________________
