### ISSUE TITLE
Edits to metadata labels above table

### ISSUE THREAD

**Issue by arouault** [MAPC/datacommon#67]
- [ ] Hide schema from user on table view

**Additional metadata fields to show from within the name field for each tabular dataset**

- creator  (Source)
- descriptn (Description)
- moddate (Date last modified)
- coverage (Coverage)

possible extras
-datesavail (Dates Available) - depending on how the different dates are going to be shown
- tbl_table (Table Name) - would be nice to have if there is space

**Comment by mzagaja** [comment]
1. Add note in view that when no datasets are selected that all are selected.
2. Update formattedMetadata computed property to ingest geospatial table properties and append to top of column metadata.
3. Update formattedMetadata computed property to recognize tabular metadata and pass it through without changes/edits.
4. Update view template to reference only formattedMetadata instead of directly referencing the metadata from the tabular metadata.

**Comment by mzagaja** [comment]
Since it will only show all rows when there are no years to select at all I think adding helper text is unnecessary. The tabular data should follow the same behavior as before.
