### ISSUE TITLE
Load in geospatial topics/subtopics

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/datacommon#69]
The tabular topics/subtopic categories for tabular data are pulled in from a table that Susan manages in her databases. The one that is currently pulled in comes from her external(ish) database that currently doesn't have a domain name associated with it. I've asked her to move that table to db.live:5433, a task which she says she has now completed but I have not yet confirmed. 

During our last meeting, I asked her about the nature of the manifest table for geospatial data and she said that it was of the same form, although the category names might be a little different. I do not have the location of where or what that table is called so you will have to get that from Susan.

Once that table has been located and loaded in, you just need to ensure that the geospatial data is categorized and linked.

- [x] Ask Susan for geospatial categories table
- [x] Load in the categories and join them to the currently loaded tabular categories
- [x] Confirm that new tables are findable from the topic/subtopic lists

**Comment by mzagaja** [comment]
Is there a reason we cannot put these into the geospatial metadata file that we're already shipping to the client and extract them from there? Also, why are we unable to simply locate the geospatial datasets from the query of available tables from CartoDB?

**Comment by ericyoungberg** [comment]
It's not about locating datasets, it's about describing them through categories. We can't do it through the metadata because the metadata describes what's in the table while the manifest describes how all of the tables are categorically related.

**Comment by mzagaja** [comment]
After talking with @ericyoungberg it was learned that the initial plating of tabular data occurs in `app/adapters/application.js:9` and you can see the reference to the `environment.js:9` file. Currently, the application is pulling the `_data_browser` table from Carto and using it to categorize the tables in the data browser.

I then talked with Susan and it was decided that instead of having multiple index tables to pull in we can simply append a "database" column to the existing `_data_browser` table. Susan then added two test entries for geospatial data to the `_data_browser` table.

Next steps on this on my end are to set up a sync that is more frequent than regular syncs for the self-hosted Carto to the `_data_browser` table as data sets will not appear until this special table syncs.

We also need to point the existing data browser app to self-hosted Carto instead of our hosted version.

Then I can do the other steps enumerated by Eric above.

**Comment by mzagaja** [comment]
As far as I can tell the minimum amount of time we need to sync data with the `_data_browser` table is 1 hour. So I set it to that. However this does render the half hour sync interval we have for geospatial syncing moot.

I have also learned that for geospatial data we now have a `towndata` database in addition to the `gisdata` database.

**Comment by mzagaja** [comment]
This should be largely resolved by https://github.com/MAPC/databrowser/commit/12142f0239d31aa58b986bcac384d13d4a714384.
